backend:
    name: github
    repo: DeveloperMelanie/simpler-code
    branch: main

media_folder: static/img
public_folder: /img

collections:
    - name: terms-buyers
      label: T&C Buyers
      folder: content/pages/terms-buyers
      create: true
      fields:
          - { name: pageTitle, label: Page Title, widget: string }
          - { name: slug, label: Slug, widget: string, required: true }
          - { name: title, label: Title, required: true }
          - { name: content, label: Body, widget: markdown, required: true }
          - { name: type, label: Type, widget: hidden, default: legal }
    - name: buyers-privacy-policy
      label: Privacy Policy
      folder: content/pages/buyers-privacy-policy
      create: true
      fields:
          - { name: pageTitle, label: Page Title, widget: string }
          - { name: slug, label: Slug, widget: string, required: true }
          - { name: title, label: Title, required: true }
          - { name: content, label: Body, widget: markdown, required: true }
          - { name: type, label: Type, widget: hidden, default: legal }
    - name: docs
      label: Docs
      folder: content/pages/docs
      create: true
      fields:
          - { name: pageTitle, label: Page Title, widget: string }
          - { name: slug, label: Slug, widget: string, required: true }
          - { name: title, label: Title, required: true }
          - { name: content, label: Body, widget: markdown, required: true }
          - { name: type, label: Type, widget: hidden, default: guide }
    - name: faq
      label: FAQ
      folder: content/pages/faq
      create: true
      fields:
          - { name: pageTitle, label: Page Title, widget: string }
          - { name: slug, label: Slug, widget: string, required: true }
          - { name: title, label: Title, required: true }
          - {
                name: cards,
                label: Cards,
                widget: list,
                required: true,
                fields:
                    [
                        {
                            name: title,
                            label: Title,
                            widget: string,
                            required: true,
                        },
                        {
                            name: description,
                            label: Description,
                            widget: text,
                            required: true,
                        },
                        {
                            name: buttonText,
                            label: Button Text,
                            widget: string,
                            required: true,
                        },
                    ],
            }
          - { name: content, label: Body, widget: markdown, required: true }
          - { name: type, label: Type, widget: hidden, default: faq }
    - name: pricing
      label: Pricing
      folder: content/pages/pricing
      create: true
      fields:
          - { name: pageTitle, label: Page Title, widget: string }
          - { name: slug, label: Slug, widget: string, required: true }
          - { name: title, label: Title, required: true }
          - { name: subtitle, label: Subtitle, widget: string }
          - {
                name: destacatedCard,
                label: Destacated Card,
                widget: object,
                required: true,
                fields:
                    [
                        {
                            name: title,
                            label: Title,
                            widget: string,
                            required: true,
                        },
                        {
                            name: description,
                            label: Description,
                            widget: markdown,
                            required: true,
                        },
                        {
                            name: buttonText,
                            label: Button Text,
                            widget: string,
                            required: true,
                        },
                        {
                            name: buttonLink,
                            label: Button Link,
                            widget: string,
                            required: true,
                        },
                    ],
            }
          - {
                name: secondaryCard,
                label: Secondary Card,
                widget: object,
                required: true,
                fields:
                    [
                        {
                            name: title,
                            label: Title,
                            widget: string,
                            required: true,
                        },
                        {
                            name: description,
                            label: Description,
                            widget: markdown,
                            required: true,
                        },
                        {
                            name: buttonText,
                            label: Button Text,
                            widget: string,
                            required: true,
                        },
                        {
                            name: buttonLink,
                            label: Button Link,
                            widget: string,
                            required: true,
                        },
                    ],
            }
          - { name: type, label: Type, widget: hidden, default: pricing }
